### ISSUE TITLE
Possible Incorrect Parameter Name in breeze.tooling/TypeScriptModuleGen/gulpfile.js

### ISSUE THREAD

**Issue by larryfura** [Breeze/breeze.tooling#10]
Hello,

I think you may have parameter name wrong in the breeze.tooling/TypeScriptModuleGen/gulpfile.js file.  By default you have the parameter called baseClassName but I believe it is supposed to be baseClassFileName.

Prior to making this change it would generate the typescript files but would not include the reference to the EntityBase or my various navigation properties.  The output when running gulp generate would also state BaseClass: undefined.

Once I made the change things worked properly.

Thank you.

**Comment by marcelgood** [comment]
Do me a favor and pull the latest code. I recently updated and the parameter name is one of the fixes that should be in there now.

**Comment by larryfura** [comment]
I downloaded the updated code and you are correct.  It does work fine now without having to change the name of the parameter.  It looks like I downloaded the code I was running just a few days before you made the change.  Thanks for your help.
