### ISSUE TITLE
Tooling for .NET Core 

### ISSUE THREAD

**Issue by fayeeg** [Breeze/breeze.tooling#17]
Is MetaDataGenerator available for EF Core DLL?

Thanks & regards,
Fayeeg

**Comment by marcelgood** [comment]
No, not at this point.

**Comment by fayeeg** [comment]
Thanks for your response.

I have almost done porting MetadataGenerator to .NET Core. I am stuck at
the below point, Could you please assist? If required I can send you the
project.

provider.MetaData() throws "Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of
an object."

Looks like the connectionstring issue. I have DefaultConnection in
appsettings.json however I have to clue how to supply this to
PersistenceManager instance.


  private static string GetMetadataFromType(Type type)
        {
            try
            {

                var providerType =
typeof(EFPersistenceManager<>).MakeGenericType(type);
                var provider = (PersistenceManager)
Activator.CreateInstance(providerType);

                var metadata = provider.Metadata();

                return metadata;
            }

            catch (Exception ex)
            {
                Console.WriteLine("An exception was thrown while processing
{0}. {1}", type.FullName, ex.InnerException.StackTrace);
            }
            return string.Empty;
        }
}

**Comment by mikethibault** [comment]
Hey guys, I added a pull request that supports EF Core 2.1.  You have to have your application generate a .Net Standard DLL alongside your Core DLL, but it does work.  Notes are in the updated readme if you're interested.

**Comment by steveschmitt** [comment]
This is obsolete, because .NET Core apps can generate the metadata from the command line without needing a separate tool.

See, for example, [metadata generation in the Northwind Demo](https://github.com/Breeze/northwind-demo/blob/master/server/STEPS-Server-NET5.md#configure-the-program-class-to-generate-metadata)
