### ISSUE TITLE
Breeze .NET server side / Metadata Generator for .Net Core 3.0

### ISSUE THREAD

**Issue by fayeeg** [Breeze/breeze.tooling#23]
Hi,
Since .NET Core 2.2 will reach End of Life on December 23, 2019, any plans that you will offer your server side packages on .Net core 3.x ?

I tried upgrading the Metadatagenerator EF core project and I am getting the below error

System.MissingMethodException : Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IProperty.get_ClrType

We wish to start our new project using .Net core 3.1 and would like to use breeze client/server libraries. Looking forward to your solution. Thanks in advance.

**Comment by softronsts** [comment]
Thank you for your quick work Breeze team. Now Breeze officially supports .Net core 3.1

**Comment by steveschmitt** [comment]
We now support up to .NET 7.

Regarding metadata generation, you don't need a separate tool in .NET Core.  See [metadata generation in Northwind demo](https://github.com/Breeze/northwind-demo/blob/master/server/STEPS-Server-NET5.md#configure-the-program-class-to-generate-metadata) for an example of how to do it.
