### ISSUE TITLE
Request to publish npm pakage

### ISSUE THREAD

**Issue by nchetankini** [Breeze/breeze.tooling#34]
Hi,

Could you consider publishing breeze-entity-generator to npm, with a version number of 1.1.0?

**Comment by steveschmitt** [comment]
Done.  Please see https://www.npmjs.com/package/breeze-entity-generator

Changes include:
 - Support for nullable type (thanks @nchetankini)
 - Add section for module level codes
 - Add support for breeze-client versions that have .mjs modules and not umd (breeze-client@mjs)
 - Note: `generate()` function is now async
 - Update dependencies
 - Move version to 1.1.0

**Comment by christianacca** [comment]
Great thanks Steve
