### ISSUE TITLE
Does not work with csdl metadata in xml format

### ISSUE THREAD

**Issue by jdkb123** [Breeze/breeze.tooling#5]
-> node .\tsgen.js -input metadata.xml
-> Unexpected error occurred: Unexpected token < in JSON at position 0

metadata.xml is like this http://services.odata.org/V4/TripPinServiceRW/$metadata

**Comment by marcelgood** [comment]
That's correct. It only works with the formats supported by Breeze, which are JSON csdl or JSON native. You have to provide the metadata in one of the two supported formats.
